/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.organizacija;

import domen.Organizacija;
import java.awt.Component;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;

/**
 *
 * @author Ivana
 */
public class FrmAzuriranjeOrganizacije extends javax.swing.JPanel {

    /**
     * Creates new form FrmAzuriranjeOrganizacije
     */
    public FrmAzuriranjeOrganizacije() {
        initComponents();
        popuniKomboBoks();
        formatirajPolja(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbListaOrganizacija = new javax.swing.JComboBox();
        jpUnosOrganizacije = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNazivOrganizacije = new javax.swing.JTextField();
        jtfImeOsnivaca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfOpisDelatnosti = new javax.swing.JTextArea();
        jbtSacuvaj = new javax.swing.JButton();
        jbtPonisti = new javax.swing.JButton();
        jdcDatumOsnivanja = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jtfOrganizacijaID = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ažuriranje organizacije", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 1, 10))); // NOI18N
        setMinimumSize(new java.awt.Dimension(100, 100));
        setName(""); // NOI18N

        jLabel1.setText("Izaberite organizaciju:");

        jcbListaOrganizacija.setBackground(new java.awt.Color(255, 0, 255));
        jcbListaOrganizacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbListaOrganizacijaActionPerformed(evt);
            }
        });

        jpUnosOrganizacije.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        jLabel2.setText("Naziv organizacije:");

        jLabel3.setText("Ime i prezime osnivača:");

        jLabel4.setText("Datum osnivanja:");

        jLabel5.setText("Opis delatnosti:");

        jtfImeOsnivaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfImeOsnivacaActionPerformed(evt);
            }
        });

        jtfOpisDelatnosti.setColumns(20);
        jtfOpisDelatnosti.setRows(5);
        jScrollPane1.setViewportView(jtfOpisDelatnosti);

        jbtSacuvaj.setText("Sačuvaj promene");
        jbtSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSacuvajActionPerformed(evt);
            }
        });

        jbtPonisti.setText("Poništi promene");
        jbtPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPonistiActionPerformed(evt);
            }
        });

        jLabel6.setText("Id organizacije :");

        javax.swing.GroupLayout jpUnosOrganizacijeLayout = new javax.swing.GroupLayout(jpUnosOrganizacije);
        jpUnosOrganizacije.setLayout(jpUnosOrganizacijeLayout);
        jpUnosOrganizacijeLayout.setHorizontalGroup(
            jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUnosOrganizacijeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpUnosOrganizacijeLayout.createSequentialGroup()
                        .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfImeOsnivaca)
                            .addComponent(jtfNazivOrganizacije)
                            .addComponent(jdcDatumOsnivanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jtfOrganizacijaID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpUnosOrganizacijeLayout.createSequentialGroup()
                        .addComponent(jbtSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jbtPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpUnosOrganizacijeLayout.setVerticalGroup(
            jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUnosOrganizacijeLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfOrganizacijaID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNazivOrganizacije, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfImeOsnivaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcDatumOsnivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jpUnosOrganizacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSacuvaj)
                    .addComponent(jbtPonisti))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpUnosOrganizacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(98, 98, 98)
                        .addComponent(jcbListaOrganizacija, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbListaOrganizacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpUnosOrganizacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfImeOsnivacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfImeOsnivacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfImeOsnivacaActionPerformed

    private void jcbListaOrganizacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbListaOrganizacijaActionPerformed
        popuniPolja();
    }//GEN-LAST:event_jcbListaOrganizacijaActionPerformed

    private void jbtSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSacuvajActionPerformed
        try {
            Organizacija o = new Organizacija();
            o.setOrganizacijaID(Integer.parseInt(jtfOrganizacijaID.getText()));
            o.setImeOsnivaca(jtfImeOsnivaca.getText());
            o.setNazivOrganizacije(jtfNazivOrganizacije.getText().trim());
            o.setOpisDelatnosti(jtfOpisDelatnosti.getText());
            o.setDatumOsnivanja(jdcDatumOsnivanja.getDate());
            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konstante.IZMENI_ORGANIZACIJU);
            toz.setParametar(o);
            Komunikacija.vratiObjekat().posaljiZahtev(toz);
            TransferObjekatOdgovor too = Komunikacija.vratiObjekat().procitajOdgovor();
            JOptionPane.showMessageDialog(jpUnosOrganizacije, "Uspesno ste izmenili organizaciju", "Izmena organizacije", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(""+too.getOdgovor());
        } catch (IOException ex) {
            Logger.getLogger(FrmAzuriranjeOrganizacije.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmAzuriranjeOrganizacije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtSacuvajActionPerformed

    private void jbtPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPonistiActionPerformed
        popuniPolja();
    }//GEN-LAST:event_jbtPonistiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtPonisti;
    private javax.swing.JButton jbtSacuvaj;
    private javax.swing.JComboBox jcbListaOrganizacija;
    private com.toedter.calendar.JDateChooser jdcDatumOsnivanja;
    private javax.swing.JPanel jpUnosOrganizacije;
    private javax.swing.JTextField jtfImeOsnivaca;
    private javax.swing.JTextField jtfNazivOrganizacije;
    private javax.swing.JTextArea jtfOpisDelatnosti;
    private javax.swing.JTextField jtfOrganizacijaID;
    // End of variables declaration//GEN-END:variables

    private void popuniKomboBoks() {
        try {
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.VRATI_SVE_ORGANIZACIJE);
            Komunikacija.vratiObjekat().posaljiZahtev(toZahtev);
            TransferObjekatOdgovor too = Komunikacija.vratiObjekat().procitajOdgovor();
            List<Organizacija> listaOrganizacija = (List<Organizacija>) too.getRezultat();
            jcbListaOrganizacija.setModel(new DefaultComboBoxModel(listaOrganizacija.toArray()));
        } catch (IOException ex) {
            Logger.getLogger(FrmBrisanjeOrganizacije.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmBrisanjeOrganizacije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniPolja() {
        formatirajPolja(true);
        jtfOrganizacijaID.setEnabled(false);
        Organizacija o = (Organizacija) jcbListaOrganizacija.getSelectedItem();
        jtfOrganizacijaID.setText(String.valueOf(o.getOrganizacijaID()));
        jtfNazivOrganizacije.setText(o.getNazivOrganizacije());
        jtfImeOsnivaca.setText(o.getImeOsnivaca());
        jdcDatumOsnivanja.setDate(o.getDatumOsnivanja());
        jtfOpisDelatnosti.setText(o.getOpisDelatnosti());
    }

    private void formatirajPolja(Boolean b) {
        for (Component c : jpUnosOrganizacije.getComponents()) {
            c.setEnabled(b);
        }
        jtfOpisDelatnosti.setEnabled(b);
    }

}
