/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.organizacija.FrmUnosOrganizacije;
import java.awt.BorderLayout;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author Ivana
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    private JPanel aktivniPanel ;
    public FrmGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jmiDodavanjeOrganizacije = new javax.swing.JMenuItem();
        jmiAzuriranjeOrganizacije = new javax.swing.JMenuItem();
        jmiBrisanjeOrganizacije = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiDodavanjeClana = new javax.swing.JMenuItem();
        jmiAzuriranjeClana = new javax.swing.JMenuItem();
        jmiBrisanjeClana = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiDodavanjeZivotinje = new javax.swing.JMenuItem();
        jmiAzuriranjeZivotinje = new javax.swing.JMenuItem();
        jmiBrisanjeZivotinje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(240, 217, 163));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(640, 700));
        setPreferredSize(new java.awt.Dimension(640, 199));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/maca.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpPanel.setMinimumSize(new java.awt.Dimension(630, 0));
        jpPanel.setPreferredSize(new java.awt.Dimension(630, 0));
        jpPanel.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 630, 360));

        jMenuBar1.setBackground(new java.awt.Color(223, 205, 164));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(333333, 32769));

        jMenu4.setText("Početna!     ");
        jMenuBar1.add(jMenu4);

        jMenu1.setText("Organizacija     ");

        jmiDodavanjeOrganizacije.setText("Dodavanje nove organizacije");
        jmiDodavanjeOrganizacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodavanjeOrganizacijeActionPerformed(evt);
            }
        });
        jMenu1.add(jmiDodavanjeOrganizacije);

        jmiAzuriranjeOrganizacije.setText("Ažuriranje organizacije");
        jMenu1.add(jmiAzuriranjeOrganizacije);

        jmiBrisanjeOrganizacije.setText("Brisanje organizacije");
        jMenu1.add(jmiBrisanjeOrganizacije);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Član     ");

        jmiDodavanjeClana.setText("Dodavanje novog člana");
        jMenu2.add(jmiDodavanjeClana);

        jmiAzuriranjeClana.setText("Ažuriranje člana");
        jMenu2.add(jmiAzuriranjeClana);

        jmiBrisanjeClana.setText("Brisanje člana");
        jMenu2.add(jmiBrisanjeClana);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Životinja");

        jmiDodavanjeZivotinje.setText("Dodavanje nove životinje");
        jMenu3.add(jmiDodavanjeZivotinje);

        jmiAzuriranjeZivotinje.setText("Ažuriranje životinje");
        jMenu3.add(jmiAzuriranjeZivotinje);

        jmiBrisanjeZivotinje.setText("Brisanje životinje");
        jMenu3.add(jmiBrisanjeZivotinje);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiDodavanjeOrganizacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodavanjeOrganizacijeActionPerformed
        FrmUnosOrganizacije f = new FrmUnosOrganizacije();
        postaviAktivniPanel(f);
    }//GEN-LAST:event_jmiDodavanjeOrganizacijeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAzuriranjeClana;
    private javax.swing.JMenuItem jmiAzuriranjeOrganizacije;
    private javax.swing.JMenuItem jmiAzuriranjeZivotinje;
    private javax.swing.JMenuItem jmiBrisanjeClana;
    private javax.swing.JMenuItem jmiBrisanjeOrganizacije;
    private javax.swing.JMenuItem jmiBrisanjeZivotinje;
    private javax.swing.JMenuItem jmiDodavanjeClana;
    private javax.swing.JMenuItem jmiDodavanjeOrganizacije;
    private javax.swing.JMenuItem jmiDodavanjeZivotinje;
    private javax.swing.JPanel jpPanel;
    // End of variables declaration//GEN-END:variables

      private void postaviAktivniPanel(JPanel panel) {
        if (aktivniPanel != null) {
            this.remove(aktivniPanel);
        }
        this.jpPanel.add(panel);
        aktivniPanel = panel;
        repaint();
        validate();
    }





}
