/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.zivotinja;

import javax.swing.JOptionPane;

/**
 *
 * @author Ivana
 */
public class FrmBrisanjeZivotinje extends javax.swing.JPanel {

    /**
     * Creates new form FrmBrisanjeZivotinje
     */
    public FrmBrisanjeZivotinje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtPronadjiYivotinje = new javax.swing.JButton();
        jbtPrikaziSveZivotinje = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTabelaZivotinja = new javax.swing.JTable();
        jlKriterijumiKursa = new javax.swing.JLabel();
        jbtObrisi = new javax.swing.JButton();
        jtfKriterijumPretrage = new javax.swing.JTextField();
        jlUnesiteKriterijumPretrageKursa = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Brisanje životinje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10))); // NOI18N

        jbtPronadjiYivotinje.setText("Pronađi");
        jbtPronadjiYivotinje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPronadjiYivotinjeActionPerformed(evt);
            }
        });

        jbtPrikaziSveZivotinje.setText("Prikaži sve organizacije");
        jbtPrikaziSveZivotinje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrikaziSveZivotinjeActionPerformed(evt);
            }
        });

        jtblTabelaZivotinja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblTabelaZivotinja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTabelaZivotinjaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblTabelaZivotinja);

        jlKriterijumiKursa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlKriterijumiKursa.setText("naziv");

        jbtObrisi.setText("Obriši organizaciju");

        jtfKriterijumPretrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKriterijumPretrageActionPerformed(evt);
            }
        });

        jlUnesiteKriterijumPretrageKursa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlUnesiteKriterijumPretrageKursa.setText("Unesite kriterijum pretrage :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlUnesiteKriterijumPretrageKursa)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlKriterijumiKursa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtPronadjiYivotinje))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtfKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtPrikaziSveZivotinje, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUnesiteKriterijumPretrageKursa)
                    .addComponent(jtfKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlKriterijumiKursa)
                    .addComponent(jbtPronadjiYivotinje))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtObrisi)
                    .addComponent(jbtPrikaziSveZivotinje))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtPronadjiYivotinjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPronadjiYivotinjeActionPerformed

    }//GEN-LAST:event_jbtPronadjiYivotinjeActionPerformed

    private void jbtPrikaziSveZivotinjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrikaziSveZivotinjeActionPerformed

    }//GEN-LAST:event_jbtPrikaziSveZivotinjeActionPerformed

    private void jtblTabelaZivotinjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTabelaZivotinjaMouseClicked
        // TODO add your handling code here:
        int row = jtblTabelaZivotinja.rowAtPoint(evt.getPoint());
        int col = jtblTabelaZivotinja.columnAtPoint(evt.getPoint());
        if ( col == 2) {
            String opis = (String) jtblTabelaZivotinja.getModel().getValueAt(row, col);
            JOptionPane.showMessageDialog(this, opis, "Opis kursa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jtblTabelaZivotinjaMouseClicked

    private void jtfKriterijumPretrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfKriterijumPretrageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfKriterijumPretrageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtObrisi;
    private javax.swing.JButton jbtPrikaziSveZivotinje;
    private javax.swing.JButton jbtPronadjiYivotinje;
    private javax.swing.JLabel jlKriterijumiKursa;
    private javax.swing.JLabel jlUnesiteKriterijumPretrageKursa;
    private javax.swing.JTable jtblTabelaZivotinja;
    private javax.swing.JTextField jtfKriterijumPretrage;
    // End of variables declaration//GEN-END:variables
}
